// category.js
export const CATEGORIES = [
  "Cookies",
  "Muffins",
  "Cinnamon Roll",
  "Cupcake",
  "Cream",
  "Tiramisu / Teramisu",
  "Brownies brookei & blondei",
  "Tea Cakes / tea cakes",
  "Cheesecakes",
  "Boxes",
  "Gateaux / gateaux",
  "Celebration Cakes / celebration cakes",
  "Milk Cakes",
  "Tarts",
  "Dessert In Cups",
  "Sauce",
  "Crunchy",
  "Ganash",
  "Toffee",
  "Pastry",
  "kuku",
  "zmr",
  "Lali",
  "Crumble",
  "Fruit Mix",
  "Cakes"
];
