[
  { "id": 1, "name": "Sliced irani pistachio", "price": 12 },
  { "id": 2, "name": "Belgium gourmet", "price": 7.1 },
  { "id": 3, "name": "Lurpak Butter", "price": 2.055 },
  { "id": 4, "name": "Oil Minara", "price": 3.46 },
  { "id": 5, "name": "Sis brown sugar", "price": 1.55 },
  { "id": 6, "name": "White sugar", "price": 0.412 },
  { "id": 7, "name": "Flour al kareef", "price": 0.25 },
  { "id": 8, "name": "Baking Soda", "price": 0.48 },
  { "id": 9, "name": "Nezo salt", "price": 0.31 },
  { "id": 10, "name": "Corn starch (daily fresh)", "price": 0.82 },
  { "id": 11, "name": "Hazelnut paste", "price": 8 },
  { "id": 12, "name": "Hazelnut", "price": 7.9 },
  { "id": 13, "name": "Felchin chocolate", "price": 9.5 },
  { "id": 14, "name": "Coco powder", "price": 8.6 },
  { "id": 15, "name": "White Chocolate", "price": 6.6 },
  { "id": 16, "name": "Whipping cream", "price": 2.625 },
  { "id": 17, "name": "Nutella", "price": 4.32 },
  { "id": 18, "name": "Milk", "price": 0.55 },
  { "id": 19, "name": "Nescafe Gold Coffee", "price": 5.065 },
  { "id": 20, "name": "Callebaut Milk Chocolate", "price": 10 },
  { "id": 21, "name": "Crunchy For Cloud Cake", "price": 3.455 },
  { "id": 22, "name": "Baking powder", "price": 0.38 },
  { "id": 23, "name": "Condensed milk", "price": 1.7 },
  { "id": 24, "name": "Tea Milk", "price": 0.91 },
  { "id": 25, "name": "Saffron", "price": 4.5 },
  { "id": 26, "name": "Brown sugar", "price": 0.3 },
  { "id": 27, "name": "Salt", "price": 0.625 },
  { "id": 28, "name": "Oil", "price": 1.3 },
  { "id": 29, "name": "Belgium garmet Chocolate", "price": 68.8 },
  { "id": 30, "name": "Eggs", "price": 0.062 },
  { "id": 31, "name": "Vanilla Essence", "price": 7.875 },
  { "id": 32, "name": "Chocolate van", "price": 8 },
  { "id": 33, "name": "Philadelphia", "price": 4.5 },
  { "id": 34, "name": "Hajdu", "price": 2.2 },
  { "id": 35, "name": "Mascapone", "price": 3.39 },
  { "id": 36, "name": "Self Raising Flour", "price": 0.65 },
  { "id": 37, "name": "Cinnamon powder", "price": 3.5 },
  { "id": 38, "name": "Date Paste", "price": 4.8 },
  { "id": 39, "name": "Walnut", "price": 8.5 },
  { "id": 40, "name": "Almond Slices", "price": 9 },
  { "id": 41, "name": "Lotus smooth", "price": 5.975 },
  { "id": 42, "name": "Fleur De Sel Salt", "price": 7.2 },
  { "id": 43, "name": "Date Cake Sauce", "price": 1.144 },
  { "id": 44, "name": "Galaxy Milk Chocolate", "price": 0.36 },
  { "id": 45, "name": "Frozen Strawberry", "price": 0.55 },
  { "id": 46, "name": "Frozen Raspberry", "price": 2.28 },
  { "id": 47, "name": "Sauce Japanese cheesecake", "price": 0.516 },
  { "id": 48, "name": "Strawberry Tart Base", "price": 1.664 },
  { "id": 49, "name": "Mousseline Cream", "price": 0.969 },
  { "id": 50, "name": "Nutella Ganash", "price": 0.563 },
  { "id": 51, "name": "Pistachio slice (Irani)", "price": 11.6 },
  { "id": 52, "name": "Whole pistachio (Irani)", "price": 7.4 },
  { "id": 53, "name": "Almond slice (USA)", "price": 4 },
  { "id": 54, "name": "Almond powder", "price": 4.1 },
  { "id": 55, "name": "Full almond (USA)", "price": 3.7 },
  { "id": 56, "name": "Almond powder (USA)", "price": 4.2 },
  { "id": 57, "name": "Pecan (USA)", "price": 6.9 },
  { "id": 58, "name": "Hazelnuts (Turkey)", "price": 7.9 },
  { "id": 59, "name": "Small cashew (Vietnam)", "price": 3.7 },
  { "id": 60, "name": "Big cashew (India)", "price": 4.8 },
  { "id": 61, "name": "Golden raisins (Irani)", "price": 1.9 },
  { "id": 62, "name": "Black raisins (Afghani)", "price": 2.1 },
  { "id": 63, "name": "Cardamom 8 mm (India)", "price": 14.7 },
  { "id": 64, "name": "Sunflower seeds", "price": 1.6 },
  { "id": 65, "name": "Pumpkin seeds", "price": 2.1 },
  { "id": 66, "name": "Chia seeds (India)", "price": 2.7 },
  { "id": 67, "name": "Small prawns (Irani)", "price": 2.7 },
  { "id": 68, "name": "Toffee", "price": 0.902 },
  { "id": 69, "name": "Glucose", "price": 5.58 },
  { "id": 70, "name": "Ganash for toffee Cake", "price": 2.761 },
  { "id": 71, "name": "Capilano Pure Honey 1kg", "price": 4.25 },
  { "id": 72, "name": "Sliced irani pistachio2", "price": 12 },
  { "id": 73, "name": "Zucchini", "price": 0.65 },
  { "id": 74, "name": "Raisins", "price": 2.4 },
  { "id": 75, "name": "Kusa (Zucchini)", "price": 0.65 },
  { "id": 76, "name": "Self rising flour", "price": 0.35 },
  { "id": 77, "name": "Pistachio slice", "price": 8.5 },
  { "id": 78, "name": "Candia French whipping cream", "price": 2.5 },
  { "id": 79, "name": "Nutella chocolate", "price": 4.32 },
  { "id": 80, "name": "1 PC Eggs", "price": 0.062 },
  { "id": 81, "name": "Fresh Carrot", "price": 0.45 },
  { "id": 82, "name": "Vanilla", "price": 7.875 },
  { "id": 83, "name": "Oil Noor canola oil", "price": 1.1 },
  { "id": 84, "name": "Butter almaraai", "price": 4.32 },
  { "id": 85, "name": "Rose Water", "price": 0.45 },
  { "id": 86, "name": "Cardamom Powder", "price": 1.2 },
  { "id": 87, "name": "Crushed Pistachio", "price": 1.85 },
  { "id": 88, "name": "Coconut Milk", "price": 0.65 },
  { "id": 89, "name": "Cocoa Powder", "price": 0.79 },
  { "id": 90, "name": "Red Food Color", "price": 0.215 },
  { "id": 91, "name": "Orange Blossom Water", "price": 0.54 },
  { "id": 92, "name": "Glucose Syrup", "price": 2.79 },
  { "id": 93, "name": "Kiri Cheese", "price": 5.02 },
  { "id": 94, "name": "Raffaello", "price": 2.12 },
  { "id": 95, "name": "Dark Chocolate Felchlin", "price": 8.5 },
  { "id": 96, "name": "Sliced irani indian", "price": 12 },
  { "id": 97, "name": "White Sugar", "price": 0.4 },
  { "id": 98, "name": "Desiccated Coconut", "price": 2.95 }
]
