export const STOCK_DATA = [
  { "id": 1, "name": "Sliced irani pistachio", "price": 0.0 },
  { "id": 2, "name": "Belgium gourmet", "price": 7.1 },
  { "id": 3, "name": "Lurpak Butter", "price": 2.055 },
  { "id": 4, "name": "Oil Minara", "price": 3.46 },
  { "id": 5, "name": "Sis brown sugar", "price": 1.55 },
  { "id": 6, "name": "White sugar", "price": 0.412 },
  { "id": 7, "name": "Flour al kareef", "price": 0.25 },
  { "id": 8, "name": "Baking Soda", "price": 0.48 },
  { "id": 9, "name": "Nezo salt", "price": 0.31 },
  { "id": 10, "name": "Corn starch (daily fresh)", "price": 0.0 },
  { "id": 11, "name": "Hazelnut paste", "price": 8.0 },
  { "id": 12, "name": "Hazelnut", "price": 7.9 },
  { "id": 13, "name": "Felchin chocolate", "price": 9.5 },
  { "id": 14, "name": "Coco powder", "price": 8.6 },
  { "id": 15, "name": "White Chocolate", "price": 6.6 },
  { "id": 16, "name": "Whipping cream", "price": 2.625 },
  { "id": 17, "name": "Nutella", "price": 4.32 },
  { "id": 18, "name": "Milk", "price": 0.55 },
  { "id": 19, "name": "Nescafe Gold Coffee", "price": 5.0 },
  { "id": 20, "name": "Callebaut Milk Chocolate", "price": 0.0 },
  { "id": 21, "name": "Crunchy For Cloud Cake", "price": 0.0 },
  { "id": 22, "name": "Baking powder", "price": 0.38 },
  { "id": 23, "name": "Condensed milk", "price": 1.7 },
  { "id": 24, "name": "Tea Milk", "price": 0.91 },
  { "id": 25, "name": "Saffron", "price": 4.5 },
  { "id": 26, "name": "Brown sugar", "price": 0.3 },
  { "id": 27, "name": "Salt", "price": 0.625 },
  { "id": 28, "name": "Oil", "price": 1.3 },
  { "id": 29, "name": "Belgium garmet Chocolate", "price": 0.0 },
  { "id": 30, "name": "Eggs", "price": 0.062 },
  { "id": 31, "name": "Vanilla Essence", "price": 7.875 },
  { "id": 32, "name": "Chocolate van", "price": 8.0 },
  { "id": 33, "name": "Philadelphia", "price": 4.5 },
  { "id": 34, "name": "Hajdu", "price": 2.2 },
  { "id": 35, "name": "Mascapone", "price": 3.39 },
  { "id": 36, "name": "Self Raising Flour", "price": 0.0 },
  { "id": 37, "name": "Cinnamon powder", "price": 3.5 }
];
   
